service: serverless-course

provider:
  name: aws
  runtime: nodejs8.10
  # profile: femasters
  region: eu-west-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    events:
      - http: 
          path: /api
          method: GET
          cors: true
  todos:
    handler: src/api/todos.handler
    events:
      - http: GET /todos
  todo:
    handler: src/api/todo.handler
    events:
      - http:
          path: /todo/{id}
          method: GET
          request:
            parameters: 
              id: true
          cors: true

