service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  profile: femasters
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    events:
      - http: 
          path: /api
          method: GET
          cors: true 
  todos:
    handler: src/api/todos.handler
    events:
      - http: GET /api/todos
  todo:
    handler: src/api/todo.handler
    events:
      - http:
          path: /api/todo
          method: GET
          request:
            template:
              application/json: >
                {
                  "foo": "$input.params('foo')",
                  "data": "$input.params('data')"
                }
          cors: true

